const fs=require('node:fs'), path=require('node:path');
const {JSDOM}=require('jsdom');
const ROOT=process.cwd();
const html=fs.readFileSync(path.join(ROOT,'index.html'),'utf8');
const SCRIPTS=[...html.matchAll(/<script src="([^"]+)"><\/script>/g)].map(m=>m[1].split('?')[0]);
(async()=>{
  const dom=new JSDOM(html,{url:'http://localhost:8765/',runScripts:'outside-only',pretendToBeVisual:true});
  for(const f of SCRIPTS) dom.window.eval(fs.readFileSync(path.join(ROOT,f),'utf8'));
  await new Promise(r=>dom.window.addEventListener('load',r,{once:true}));
  await new Promise(r=>dom.window.setTimeout(r,0));
  const RS=dom.window.RallySync, doc=dom.window.document;
  const t=RS.state.upsertTarget({name:'W',x:448,y:756,zoneKey:'general',gatherSeconds:300});
  const l=RS.state.upsertLead({name:'TS',x:536,y:740,marchSpeedUpPercent:25});
  RS.state.updateSettings({selectedTargetId:t.id,selectedLeadIds:[l.id]});
  RS.app.go('calculate'); RS.app.refresh();
  const row=()=>doc.querySelector('.result');
  console.log('badge before:', row().querySelector('.badge').textContent);
  const open=[...row().querySelectorAll('.result-actions button')].find(b=>b.textContent.includes('Exact time'));
  console.log('open button found:', !!open);
  open.dispatchEvent(new dom.window.Event('click',{bubbles:true}));
  console.log('panel hidden after toggle:', row().querySelector('.exact-panel').hidden);
  const input=row().querySelector('.exact-input');
  input.value='3:33';
  const setBtn=[...row().querySelectorAll('.exact-panel button')].find(b=>b.textContent.includes('Set exact'));
  console.log('set button found:', !!setBtn);
  setBtn.dispatchEvent(new dom.window.Event('click',{bubbles:true}));
  console.log('stored measurement:', JSON.stringify(RS.state.measurementFor(l.id,t.id)));
  console.log('feedback text:', row().querySelector('.exact-feedback')?.textContent);
  console.log('badge after (no refresh):', row().querySelector('.badge').textContent);
  RS.app.refresh();
  console.log('badge after refresh   :', row().querySelector('.badge').textContent);
})();
